FROM golang:1.25-alpine@sha256:8e02eb337d9e0ea459e041f1ee5eece41cbb61f1d83e7d883a3e2fb4862063fa

RUN go install github.com/air-verse/air@v1.64.5

RUN mkdir -p /tmp/go-cache/gopath /tmp/go-cache/build && chmod -R 777 /tmp/go-cache

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

EXPOSE 9106
ENTRYPOINT ["air"]
