#!/usr/bin/env bash
# Generate the Synaplan API client from Synaplan's OpenAPI spec.
#
# Two modes:
#
#   1. Pinned image (default, used by CI and fresh checkouts):
#      `docker run` the pinned synaplan image and dump the spec from
#      there. The digest is read from .github/workflows/ci.yml —
#      single source of truth, bumped by Renovate via a customManager.
#
#   2. Live source (dev iteration against a locally-modified synaplan):
#      If SYNAPLAN_SRC_CONTAINER is set, `docker exec` into that running
#      container to dump the spec instead. This picks up the current
#      on-disk source (assuming the container bind-mounts it, which the
#      standard synaplan dev stack does for /var/www/backend), so you can
#      iterate on both synaplan and synaplan-opencloud without pushing
#      an image or bumping the pinned digest.
#
#      Example:
#          SYNAPLAN_SRC_CONTAINER=synaplan-backend make generate
#
# The spec and the generated client are NEVER committed — they are
# regenerated by every `go generate` / `make generate` run.
set -euo pipefail

# Resolve paths relative to this script.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_DIR="$(cd "${BACKEND_DIR}/.." && pwd)"
GEN_DIR="${BACKEND_DIR}/internal/synaplanapi"
SPEC_FILE="${GEN_DIR}/.cache/openapi.json"
CONFIG_FILE="${GEN_DIR}/oapi-codegen.yaml"
OUTPUT_FILE="${GEN_DIR}/client.gen.go"

# Pinned digest lives in .github/workflows/ci.yml so CI and Renovate
# see a single source of truth. Grep it out when generating locally.
# Env var override is still honoured so CI can pass it directly.
if [ -z "${SYNAPLAN_IMAGE:-}" ]; then
  CI_YAML="${REPO_DIR}/.github/workflows/ci.yml"
  if [ ! -f "${CI_YAML}" ]; then
    echo "!!! Cannot find ${CI_YAML} to extract synaplan digest." >&2
    echo "!!! Set SYNAPLAN_IMAGE explicitly or run from a checkout." >&2
    exit 1
  fi
  DIGEST="$(grep -oE 'SYNAPLAN_IMAGE_DIGEST:[[:space:]]+sha256:[a-f0-9]+' "${CI_YAML}" | awk '{print $2}')"
  if [ -z "${DIGEST}" ]; then
    echo "!!! Could not extract SYNAPLAN_IMAGE_DIGEST from ${CI_YAML}." >&2
    exit 1
  fi
  SYNAPLAN_IMAGE="ghcr.io/metadist/synaplan@${DIGEST}"
fi
: "${SYNAPLAN_SRC_CONTAINER:=}"

mkdir -p "$(dirname "${SPEC_FILE}")"

if [ -n "${SYNAPLAN_SRC_CONTAINER}" ]; then
  # Live-source mode: exec into a running dev container that has the
  # synaplan source bind-mounted. No .env gymnastics needed because the
  # container already has a working .env from docker-compose.
  echo ">>> Extracting OpenAPI spec from live container: ${SYNAPLAN_SRC_CONTAINER}"
  if ! docker inspect --format='{{.State.Running}}' "${SYNAPLAN_SRC_CONTAINER}" 2>/dev/null | grep -q true; then
    echo "!!! Container '${SYNAPLAN_SRC_CONTAINER}' is not running." >&2
    echo "!!! Start the synaplan dev stack or unset SYNAPLAN_SRC_CONTAINER." >&2
    exit 1
  fi
  docker exec "${SYNAPLAN_SRC_CONTAINER}" sh -c '
    cd /var/www/backend && php bin/console nelmio:apidoc:dump --format=json
  ' > "${SPEC_FILE}"
else
  # Pinned-image mode: symfony's dotenv insists on a .env file even when
  # every var is already set, so we copy .env.test to .env inside a fresh
  # container before dumping. nelmio:apidoc:dump reads routes/attributes
  # only — no DB, Keycloak or other services needed.
  echo ">>> Extracting OpenAPI spec from pinned image: ${SYNAPLAN_IMAGE}"
  docker run --rm --entrypoint=/bin/sh "${SYNAPLAN_IMAGE}" -c '
    cd /var/www/backend
    cp .env.test .env
    APP_ENV=test php bin/console nelmio:apidoc:dump --format=json
  ' > "${SPEC_FILE}"
fi

# Sanity check — bail early if extraction silently produced something bogus.
if ! head -c 1 "${SPEC_FILE}" | grep -q '{'; then
  echo "!!! OpenAPI spec extraction produced unexpected output:" >&2
  head -c 500 "${SPEC_FILE}" >&2
  exit 1
fi

SPEC_SIZE=$(wc -c < "${SPEC_FILE}")
echo ">>> Extracted $(( SPEC_SIZE / 1024 )) KiB spec → ${SPEC_FILE}"

echo ">>> Running oapi-codegen → ${OUTPUT_FILE}"
# Run from the target directory so oapi-codegen resolves `output:` relative
# to the package dir, not the backend root. go tool still finds go.mod by
# walking upward from cwd.
cd "${GEN_DIR}"
go tool github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen \
  -config "${CONFIG_FILE}" \
  "${SPEC_FILE}"

echo ">>> Done"
