#!/usr/bin/env bash
# Generate the Synaplan API client from Synaplan's OpenAPI spec.
#
# Two modes:
#
#   1. Pinned image (default, used by CI and fresh checkouts):
#      `docker run` the pinned synaplan image and dump the spec from there.
#      The image digest MUST match SYNAPLAN_IMAGE_DIGEST in
#      .github/workflows/ci.yml so CI and local generation agree.
#
#   2. Live source (dev iteration against a locally-modified synaplan):
#      If SYNAPLAN_SRC_CONTAINER is set, `docker exec` into that running
#      container to dump the spec instead. This picks up the current
#      on-disk source (assuming the container bind-mounts it, which the
#      standard synaplan dev stack does for /var/www/backend), so you can
#      iterate on both synaplan and synaplan-opencloud without pushing
#      an image or bumping the pinned digest.
#
#      Example:
#          SYNAPLAN_SRC_CONTAINER=synaplan-backend make generate
#
# The spec and the generated client are NEVER committed — they are
# regenerated by every `go generate` / `make generate` run.
set -euo pipefail

: "${SYNAPLAN_IMAGE:=ghcr.io/metadist/synaplan@sha256:71d343f439d0de8aa46dba95946a4b7948175d27b73599ebcfc6a6a8e4e1a66d}"
: "${SYNAPLAN_SRC_CONTAINER:=}"

# Resolve paths relative to this script.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
GEN_DIR="${BACKEND_DIR}/internal/synaplanapi"
SPEC_FILE="${GEN_DIR}/.cache/openapi.json"
CONFIG_FILE="${GEN_DIR}/oapi-codegen.yaml"
OUTPUT_FILE="${GEN_DIR}/client.gen.go"

mkdir -p "$(dirname "${SPEC_FILE}")"

if [ -n "${SYNAPLAN_SRC_CONTAINER}" ]; then
  # Live-source mode: exec into a running dev container that has the
  # synaplan source bind-mounted. No .env gymnastics needed because the
  # container already has a working .env from docker-compose.
  echo ">>> Extracting OpenAPI spec from live container: ${SYNAPLAN_SRC_CONTAINER}"
  if ! docker inspect --format='{{.State.Running}}' "${SYNAPLAN_SRC_CONTAINER}" 2>/dev/null | grep -q true; then
    echo "!!! Container '${SYNAPLAN_SRC_CONTAINER}' is not running." >&2
    echo "!!! Start the synaplan dev stack or unset SYNAPLAN_SRC_CONTAINER." >&2
    exit 1
  fi
  docker exec "${SYNAPLAN_SRC_CONTAINER}" sh -c '
    cd /var/www/backend && php bin/console nelmio:apidoc:dump --format=json
  ' > "${SPEC_FILE}"
else
  # Pinned-image mode: symfony's dotenv insists on a .env file even when
  # every var is already set, so we copy .env.test to .env inside a fresh
  # container before dumping. nelmio:apidoc:dump reads routes/attributes
  # only — no DB, Keycloak or other services needed.
  echo ">>> Extracting OpenAPI spec from pinned image: ${SYNAPLAN_IMAGE}"
  docker run --rm --entrypoint=/bin/sh "${SYNAPLAN_IMAGE}" -c '
    cd /var/www/backend
    cp .env.test .env
    APP_ENV=test php bin/console nelmio:apidoc:dump --format=json
  ' > "${SPEC_FILE}"
fi

# Sanity check — bail early if extraction silently produced something bogus.
if ! head -c 1 "${SPEC_FILE}" | grep -q '{'; then
  echo "!!! OpenAPI spec extraction produced unexpected output:" >&2
  head -c 500 "${SPEC_FILE}" >&2
  exit 1
fi

SPEC_SIZE=$(wc -c < "${SPEC_FILE}")
echo ">>> Extracted $(( SPEC_SIZE / 1024 )) KiB spec → ${SPEC_FILE}"

echo ">>> Running oapi-codegen → ${OUTPUT_FILE}"
# Run from the target directory so oapi-codegen resolves `output:` relative
# to the package dir, not the backend root. go tool still finds go.mod by
# walking upward from cwd.
cd "${GEN_DIR}"
go tool github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen \
  -config "${CONFIG_FILE}" \
  "${SPEC_FILE}"

echo ">>> Done"
